[main]
font=JetBrainsMono Nerd Font:size=14
dpi-aware=no
prompt="> "
terminal=foot
layer=overlay
exit-on-keyboard-focus-loss=yes
show-actions=no

[colors]
#background=1e1e2eff
background=1e1e2ecc
text=cdd6f4ff
match=7ad3beff
selection=313244ff
selection-match=7ad3beff
selection-text=cdd6f4ff
#border=89b4faff
border=7ad3beff


[border]
width=2
radius=6

[dmenu]
mode=text
